'use client'

import { useState } from 'react'
import type { AnalysisResult } from '@/lib/types'
import { ScoreRing } from './ScoreRing'
import { CriterionGroupSection } from './CriterionGroup'
import { AgentLog } from './AgentLog'

interface ResultsViewProps {
  result: AnalysisResult & { pageTitle?: string }
  onReset: () => void
}

export function ResultsView({ result, onReset }: ResultsViewProps) {
  const [activeFilter, setActiveFilter] = useState<'all' | 'critical' | 'warning'>('all')
  const [showLog, setShowLog] = useState(false)

  const riskColor =
    result.legalRisk === 'High'   ? 'text-red-400'   :
    result.legalRisk === 'Medium' ? 'text-amber-400' :
    'text-green-400'

  const riskBg =
    result.legalRisk === 'High'   ? 'bg-red-900/40 border-red-700/40'   :
    result.legalRisk === 'Medium' ? 'bg-amber-900/40 border-amber-700/40' :
    'bg-green-900/40 border-green-700/40'

  const filteredGroups = result.criterionGroups
    .map(g => ({
      ...g,
      violations: activeFilter === 'all'
        ? g.violations
        : g.violations.filter(v => v.severity === activeFilter),
    }))
    .filter(g => g.violations.length > 0)

  const copyReport = async () => {
    const text = [
      `WCAG 2.1 AA Accessibility Report`,
      `URL: ${result.url}`,
      `Date: ${new Date(result.scannedAt).toLocaleString()}`,
      `Score: ${result.overallScore}/100 (Grade ${result.grade})`,
      `Legal Risk: ${result.legalRisk}`,
      ``,
      result.summary,
      ``,
      `VIOLATIONS (${result.allViolations.length} total):`,
      ...result.allViolations.map(v =>
        `[${v.severity.toUpperCase()}] ${v.criterionId} ${v.criterionName}\n  ${v.issue}\n  Fix: ${v.fixedCode}`
      ),
      ``,
      `Generated by AccessGuard · Powered by NVIDIA Nemotron`,
    ].join('\n')
    await navigator.clipboard.writeText(text)
  }

  return (
    <div className="max-w-5xl mx-auto px-4 pb-16 stagger">

      {/* Top actions */}
      <div className="flex items-center justify-between py-4 mb-2">
        <button
          onClick={onReset}
          className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-300 transition-colors font-mono"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <path d="M10 3L5 8l5 5"/>
          </svg>
          Analyze another site
        </button>
        <div className="flex gap-2">
          <button
            onClick={() => setShowLog(!showLog)}
            className="text-xs font-mono px-3 py-1.5 rounded-lg border border-gray-700/50 text-gray-500 hover:text-gray-300 hover:border-gray-600 transition-colors"
          >
            {showLog ? 'Hide' : 'Show'} agent log
          </button>
          <button
            onClick={copyReport}
            className="text-xs font-mono px-3 py-1.5 rounded-lg border border-gray-700/50 text-gray-400 hover:text-white hover:border-[#76b900]/50 transition-colors"
          >
            Copy report
          </button>
        </div>
      </div>

      {/* Agent log (collapsible) */}
      {showLog && (
        <div className="mb-4">
          <AgentLog log={result.agentLog} />
        </div>
      )}

      {/* Nemotron summary banner */}
      <div className="bg-gray-900 border border-[#76b900]/20 rounded-xl p-5 mb-4">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-mono text-[#76b900] uppercase tracking-wider">◎ Nemotron Analysis</span>
          <div className="h-px flex-1 bg-[#76b900]/10" />
          <span className="text-xs font-mono text-gray-600">
            {new Date(result.scannedAt).toLocaleTimeString()}
          </span>
        </div>
        <p className="text-gray-300 leading-relaxed text-sm">{result.summary}</p>
        {result.pageTitle && (
          <p className="text-xs text-gray-600 font-mono mt-2 truncate">
            {result.pageTitle} · {result.url}
          </p>
        )}
      </div>

      {/* Score + stats row */}
      <div className="grid grid-cols-1 md:grid-cols-[auto_1fr] gap-4 mb-4">
        {/* Score ring */}
        <div className="bg-gray-900/60 border border-gray-700/40 rounded-xl p-6 flex flex-col items-center justify-center gap-4">
          <ScoreRing score={result.overallScore} grade={result.grade} size={160} />
          <div className="text-center">
            <p className="text-xs text-gray-600 font-mono">WCAG 2.1 AA · {result.totalElements} elements</p>
          </div>
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-2 gap-3">
          {/* Violation counts */}
          <div className="bg-red-950/40 border border-red-800/40 rounded-xl p-4 flex flex-col justify-between">
            <p className="text-xs font-mono text-red-400/70 uppercase tracking-wider">Critical</p>
            <div>
              <p className="text-4xl font-bold text-red-400 leading-none">{result.criticalCount}</p>
              <p className="text-xs text-red-400/50 mt-1">violations</p>
            </div>
          </div>
          <div className="bg-amber-950/30 border border-amber-800/30 rounded-xl p-4 flex flex-col justify-between">
            <p className="text-xs font-mono text-amber-400/70 uppercase tracking-wider">Warnings</p>
            <div>
              <p className="text-4xl font-bold text-amber-400 leading-none">{result.warningCount}</p>
              <p className="text-xs text-amber-400/50 mt-1">violations</p>
            </div>
          </div>
          {/* Legal risk */}
          <div className={`rounded-xl p-4 border ${riskBg} flex flex-col justify-between`}>
            <p className={`text-xs font-mono uppercase tracking-wider ${riskColor} opacity-70`}>Legal Risk</p>
            <div>
              <p className={`text-2xl font-bold ${riskColor} leading-none`}>{result.legalRisk}</p>
              <div className="mt-2 h-1 bg-gray-800 rounded-full overflow-hidden">
                <div
                  className="h-full rounded-full"
                  style={{
                    width: `${result.legalRiskScore}%`,
                    background: result.legalRisk === 'High' ? '#ef4444' : result.legalRisk === 'Medium' ? '#f59e0b' : '#76b900',
                    transition: 'width 1s ease',
                  }}
                />
              </div>
              <p className={`text-xs mt-1 ${riskColor} opacity-50`}>ADA exposure score: {result.legalRiskScore}/100</p>
            </div>
          </div>
          {/* Total */}
          <div className="bg-gray-900/60 border border-gray-700/40 rounded-xl p-4 flex flex-col justify-between">
            <p className="text-xs font-mono text-gray-500 uppercase tracking-wider">Total Violations</p>
            <div>
              <p className="text-4xl font-bold text-gray-300 leading-none">{result.allViolations.length}</p>
              <p className="text-xs text-gray-600 mt-1">{result.passCount} elements passed</p>
            </div>
          </div>
        </div>
      </div>

      {/* WCAG criteria breakdown bar */}
      <div className="bg-gray-900/60 border border-gray-700/40 rounded-xl p-4 mb-4">
        <p className="text-xs font-mono text-gray-600 uppercase tracking-wider mb-3">Criteria Breakdown</p>
        <div className="flex flex-wrap gap-2">
          {result.criterionGroups.map(g => {
            const hasCritical = g.violations.some(v => v.severity === 'critical')
            const hasWarning  = g.violations.some(v => v.severity === 'warning')
            const color = hasCritical ? 'bg-red-900/60 text-red-300 border-red-700/50' :
                          hasWarning  ? 'bg-amber-900/60 text-amber-300 border-amber-700/50' :
                          'bg-green-900/60 text-green-300 border-green-700/50'
            return (
              <span key={g.criterionId} className={`text-xs font-mono px-2 py-1 rounded border ${color}`}>
                {g.criterionId} · {g.violations.length}
              </span>
            )
          })}
        </div>
      </div>

      {/* Violation filter tabs */}
      <div className="flex items-center gap-2 mb-4">
        <span className="text-xs text-gray-600 font-mono mr-1">Filter:</span>
        {(['all', 'critical', 'warning'] as const).map(f => (
          <button
            key={f}
            onClick={() => setActiveFilter(f)}
            className={`text-xs font-mono px-3 py-1.5 rounded-lg border transition-all ${
              activeFilter === f
                ? f === 'all'      ? 'bg-gray-700 text-white border-gray-500'
                : f === 'critical' ? 'bg-red-900/60 text-red-300 border-red-700/50'
                :                   'bg-amber-900/60 text-amber-300 border-amber-700/50'
                : 'bg-transparent text-gray-600 border-gray-700/40 hover:border-gray-600 hover:text-gray-400'
            }`}
          >
            {f === 'all' ? `All (${result.allViolations.length})` :
             f === 'critical' ? `Critical (${result.criticalCount})` :
             `Warnings (${result.warningCount})`}
          </button>
        ))}
      </div>

      {/* Criterion groups */}
      <div className="space-y-3">
        {filteredGroups.length === 0 ? (
          <div className="text-center py-12 text-gray-600 font-mono text-sm">
            No {activeFilter} violations found.
          </div>
        ) : (
          filteredGroups.map((group, i) => (
            <CriterionGroupSection key={group.criterionId} group={group} index={i} />
          ))
        )}
      </div>
    </div>
  )
}
